import type { MindmapThemeSnapshot } from "./types";
export const MINDMAP_THEMES: readonly MindmapThemeSnapshot[] = [
  {
    id: "default",
    name: "默认",
    root: {
      shape: "rounded-rectangle",
      fill: "#5b7cfa",
      color: "#ffffff",
      stroke: "#4665d8",
      fontSize: 18,
      fontWeight: "bold",
      strokeWidth: 2.5,
    },
    branch: { shape: "text", color: "#172033", fontSize: 14 },
    leaf: { shape: "text", color: "#475569", fontSize: 13 },
    connector: "#60a5fa",
    branchColors: [],
    levelGap: 64,
    crossGap: 24,
  },
  {
    id: "simple",
    name: "简洁",
    root: {
      shape: "rounded-rectangle",
      fill: "#ffffff",
      color: "#172033",
      stroke: "#475569",
      fontSize: 18,
      fontWeight: "bold",
      strokeWidth: 1.5,
    },
    branch: { shape: "text", color: "#172033", fontSize: 14 },
    leaf: { shape: "text", color: "#475569", fontSize: 13 },
    connector: "#94a3b8",
    branchColors: [],
    levelGap: 64,
    crossGap: 24,
  },
  {
    id: "colorful",
    name: "彩色分支",
    root: {
      shape: "rounded-rectangle",
      fill: "#172033",
      color: "#ffffff",
      fontSize: 18,
      fontWeight: "bold",
    },
    branch: { shape: "rounded-rectangle", fontSize: 14 },
    leaf: { shape: "text", fontSize: 13 },
    connector: "#60a5fa",
    branchColors: [
      "#2563eb",
      "#16a34a",
      "#ea580c",
      "#9333ea",
      "#db2777",
      "#0891b2",
    ],
    levelGap: 72,
    crossGap: 28,
  },
  {
    id: "dark",
    name: "深色",
    root: {
      shape: "rounded-rectangle",
      fill: "#334155",
      color: "#f8fafc",
      stroke: "#64748b",
      fontSize: 18,
      fontWeight: "bold",
    },
    branch: { shape: "text", color: "#e2e8f0", fontSize: 14 },
    leaf: { shape: "text", color: "#cbd5e1", fontSize: 13 },
    connector: "#94a3b8",
    branchColors: [],
    levelGap: 64,
    crossGap: 24,
  },
];
export function resolveMindmapTheme(id: string) {
  return MINDMAP_THEMES.find((theme) => theme.id === id) || MINDMAP_THEMES[0];
}
